# -*- coding: utf-8 -*-
"""Pandas-Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjoZupve7ZRyvmLcLwJ5PUPDiT_6XUPB
"""

import pandas as pd

a = {"a": [1,2,3,4, " "],
     "b" : [5,6,7,8, None]}
df2= pd.DataFrame(a)
df2.head()

a = "python is easy"
b = a.split()
r = "".join(b)
print(r)
# print(b)
# output = ""
# for i in b:
#   output = output + i
# print(output)

df2.head()

df = pd.read_csv('xyz.csv')

df.head(5)

df.isnull().sum().sum()

df.sort_values(by=["Year", "Value"], ascending=[False, True], inplace=True)

df.head()

df[df["Year"] > 2023]

df[['Year', 'Variable_category']]

df.index.isin(range(0,55629))

df.loc[1]

df.loc[100:110]

df.iloc[:].values

df.loc[100:110, ['Year']]

df.iloc[:-1, :]

duplicates = df['Industry_aggregation_NZSIOC'].duplicated().count()
print(duplicates)

df.rename(columns = {'Industry_name_NZSIOC' : 'Industry_Name'}, inplace = True)

df.head(2)

df['Year'].value_counts()

df['Year'].value_counts(normalize=True)

df.head(2)

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

print(arr.ndim)

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr[2] + arr[3])

print(arr.dtype)

x = arr.view()
x[0] = 33
print(arr)
print(x)

y = arr.copy()
arr[0] = 42

print(arr)
print(y)

sr = df.sample(frac=0.00025)
sr.shape

df.shape

df.info()

df.dtypes

df.size

df.ndim

df.describe

df['Year'].unique()

df['Variable_code'].unique()

df['Variable_code'].nunique()

df.isna().sum().sum()

df['Year'].clip(2016, 2016, axis = 0)

df.columns

df.sort_values("Value", axis=0, ascending=True, inplace=True, na_position='last')

df.head()

df['Year'].value_counts()



df.nlargest(3, ['Year'])

df.nsmallest(1, ['Year'])

df.loc[51837, 'Units']

df.loc[51837, ['Units', 'Variable_category']]

df.loc[df['Units'] == "Percentage"]

print(df.head())

df[['Industry_Name', 'Units', 'Year']].loc[df['Units'] == "Percentage"]

data = {'a': [1,2,3,4],
        'b' : [3,4,5,6]}

cf = pd.DataFrame(data)

df.groupby(by = 'Industry_Name').count()

df['Industry_Name'].nunique()

df1 = df.transpose()

df1.head()

df.plot()

"""Input: [4, 2, 8, 1, 9]
Output:
Minimum = 1
Maximum = 9
"""

Input =  [4, 2, 8, 1, 9, 0]

a = Input[0]

print(a)

for i in Input[1: ]:
  if a > i:
    i = a
print(f'big', {i})

b = Input[0]
for x in Input[1: ]:
  if b < x:
    x = b
print(f'small', {x})

for x in Input[1: ]:
  if a < x:
    a = x
print(i)

"""Write a Python program to capitalize first letter of each word in a sentence without using title().
Input: "python is easy"
Output: "Python Is Easy"
"""

Input ="python is easy"
a = Input.split()
print(a)

# for x in Input:
x = a[0][0].upper()
print(x)

i = 0
for j in a[i: i+1]:
  j = a[i][0].upper()
print(j)

for s in a:
  m = s.upper()
  print(m)

l =
for i in a:
  for k in i:
    m = i[0].upper() + i[1:]
  print(m)

l = []
for i in a:
  for k in i:
    m = i[0].upper() + i[1:]
    l.append(m)
print(l)

for i in a:
  f = []
  for k in i:
    m = i[0].upper()
  f.append(m)
  print(f)

kl = []
aa = a[0]
kl.append(aa)
print(kl)

Input ="python is easy"
a = Input.split()
print(a)

for i in a:
  f = []
  for k in i:
    m = i[0].upper()
  f.append(m)
  print(f)

for s in a:
  q = s.split()
  print(q)
  for k in s:
    m = s[0].upper().join(s[1:])
  print(m)

for i in a:
  f = []
  for k in i:
    m = i[0].upper()
  f.append(m)
  print(f)

import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B"],
    "age": [20, 25],
    "city": ["X", "Y"]
})

df.filter(items=["name", "age"], axis=1)

df.filter(like="a", axis=1)

df.filter(regex="^a", axis=1)

df.filter(items=[0], axis=0)

