# Generated by Django 6.0.4 on 2026-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
