# Generated by Django 6.0.4 on 2026-04-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0002_books_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_id',
            new_name='author_name',
        ),
    ]
