# Generated by Django 6.0.4 on 2026-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0002_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='dont remember', max_length=60),
        ),
    ]
