# Generated by Django 6.0.4 on 2026-04-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0003_rename_author_id_books_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_name',
            new_name='author_id',
        ),
    ]
