# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmjOmnwyDVjdkQyuhegQHfWb9EsWMHRX
"""

import numpy as np

temps = np.array([30, 32, 35, 28])
print(temps + 1)

list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

# Multiply each by 2
list_result = [x * 2 for x in list1]
array_result = array1 * 2

print("List:", list_result)
print("array1:", array_result)

# 1D array
marks_1d = np.array([85, 90, 78])
print("1D:", marks_1d)

# 2D array
marks_2d = np.array([[85, 90, 78], [88, 92, 80]])
print("2D:\n", marks_2d)

# 3D array
marks_3d = np.array([[[85, 90], [78, 88]], [[92, 80], [70, 60]]])
print("3D:\n", marks_3d)

np.zeros((2, 3))

np.ones((3, 2))

np.arange(1, 10, 2)

np.linspace(0, 100, 5)

arr = np.array([1.5, 2.7, 3.1])
print(arr.dtype)

a = np.array([[1, 2, 3, 4], [4, 5, 6, 8]])
print("Shape:", a.shape)
print("Size:", a.size)

arr = np.array([10, 20, 30, 40])
print(arr[0])
arr[2] = 99
print(arr)

# 2D array
arr_2d = np.array([[5, 10], [15, 20]])
print(arr_2d[1, 0])

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5])
print(arr[::2])
print(arr[::-1])

matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(matrix[0:2, 1:3])

scores = np.array([45, 78, 89, 90, 67])
print(scores[scores > 80])

arr = np.array([10, 20, 30, 40, 50])
indice = [0, 2, 4]
print(arr[indice])

store1 = np.array([100, 150, 200])
store2 = np.array([90, 160, 210])

# Element-wise operations
print("Add:", store1 + store2)
print("Subtract:", store1 - store2)
print("Multiply:", store1 * store2)
print("Divide:", store1 / store2)

marks = np.array([60, 70, 80])
print(marks + 5)
print(marks * 2)

scores = np.array([45, 67, 88, 39])
print(scores[scores >= 50])

scores = np.array([45, 67, 88, 39])
print((scores >= 50) & (scores > 70))
print((scores >= 50) | (scores > 70))
print(~(scores >= 50) | (scores > 70))

marks = np.array([80, 90, 70, 60])
print("Total:", marks.sum())
print("Average:", marks.mean())
print("Min:", marks.min())
print("Max:", marks.max())

marks = np.array([[80, 90, 70],
[60, 85, 75]])
print(marks.sum(axis=0))
print(marks.sum(axis=1))

marks = np.array([[50, 60, 70],
[80, 90, 100]])
bonus = 10
# Broadcasting adds 10 to every element
print(marks + bonus)

grades = np.array([[85, 90, 95],
[80, 85, 90]])
curve = np.array([1, 2, 3])
print(grades + curve)

marks = np.array([[50, 60, 70],
[80, 90, 100]])
reshaped = marks.reshape(3,2)
print("Reshaped:\n", reshaped)

matrix = np.array([[1, 2, 3],
[4, 5, 6]])
flat = matrix.flatten()
print(flat)

arr = np.array([1, 2, 3, 4])
print(arr.size)
resized = np.resize(arr, (2, 3))
print(resized)
print(resized.size)

matrix = np.array([[1, 2],
[3, 4],
[5, 6]])
print("Original:\n", matrix)
print("Transposed:\n", matrix.T)

a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:\n", np.hstack((a, b)))

arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr, 3) # Split into 3 equal parts
print(split_arr)
print([split_arr[0], split_arr[2]])
print(split_arr[1][0])

matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8]])
# Split columns
left, right = np.hsplit(matrix, 2)
print("Left:\n", left)
print("Right:\n", right)

# Split rows
top, bottom = np.vsplit(matrix, 2)
print("Top:\n", top)
print("Bottom:\n", bottom)

arr = np.array([10, 20, 30, 40])
view = arr[1:3]
view[0] = 99

print("View:", view) # [99 30]
print("Original:", arr) # [10 99 30 40] ← changed!

arr = np.array([1, 2, 3, 4])
copy_arr = arr.copy()
copy_arr[0] = 99

print("Copy:", copy_arr) # [99 2 3 4]
print("Original:", arr) # [1 2 3 4] ← unchanged

fruits = np.array(['apple', 'banana', 'cherry'])
for fruit in fruits:
  print(fruit)

arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr:
  print("Row:", row)

arr = np.array([[1, 2], [3, 4]])
for val in arr.flat:
  print(val, end = " ")

arr = np.array([1, 2, 3])
for x in np.nditer(arr, op_flags=['readwrite']):
  x[...] = x * 2

print("Modified:", arr)

arr = np.array([[100, 200], [300, 400]])
for index, value in np.ndenumerate(arr):
  print(f"Index {index} has value {value}")

print(np.random.rand(3))

print(np.random.rand(2, 2))

print(np.random.randint(10, 20, size=5))

print(np.random.randn(4))
print(np.random.randn(2, 3))

items = ['apple', 'banana', 'cherry']
print(np.random.choice(items, size=2))

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled:", arr)

arr = np.array([10, 20, 30, 40])
shuffled = np.random.permutation(arr)
print("Original:", arr)
print("Shuffled Copy:", shuffled)

np.random.seed(42)
print(np.random.rand(3))

names = np.array(['Alice', 'BOB', 'ChArLiE'])
print(np.char.lower(names))
print(np.char.upper(names))

arr = np.array(['hello', 'world'])
print(np.char.capitalize(arr))

first = np.array(['John', 'Jane'])
last = np.array(['Doe', 'Smith'])
print(np.char.add(first,last))

words = np.array(['Hi', 'Bye'])
print(np.char.multiply(words, 3))

arr = np.array(['Hi', 'Hello'])
print(np.char.center(arr, 10, fillchar='*'))

sentences = np.array(['Hello World', 'Python NumPy'])
print(np.char.split(sentences))

arr = np.array([' apple ', ' banana'])
print(np.char.strip(arr))

arr = np.array(['I hate bugs', 'Bugs are bad'])
print(np.char.replace(arr, 'bugs', 'features'))

emails = np.array(['user@example.com', 'admin@site.org'])
print(np.char.find(emails, '@'))

# Array with NaN (missing) values
data = np.array([1, 2, np.nan, 4, 5, np.nan])
print(data)

# Check for NaN values
is_nan = np.isnan(data)
print("Check for NaN values:", is_nan)

# Replace NaN values with 0
cleaned_data = np.nan_to_num(data, nan=0)
print("Data After Replacing NaN with 0:", cleaned_data)

# Replace NaN values with the mean of the array
mean_value = np.nanmean(data)
filled_data = np.where(np.isnan(data), mean_value, data)
print("Data After Filling NaN with Mean:", filled_data)

arr = np.arange(1, 11)
print(arr)

matrix = np.zeros((3, 3))
print(matrix)

import numpy as np

identity = np.eye(4)
print(identity)

import numpy as np

rand_nums = np.random.rand(5)
print(rand_nums)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print(reshaped)

import numpy as np

arr = np.array([10, 20, 5, 40, 15])

print("Maximum:", arr.max())
print("Minimum:", arr.min())

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)

print(result)

import numpy as np

arr = np.arange(2, 21, 2)

print(arr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print(reversed_arr)

import numpy as np

arr = np.array([1, 6, 3, 8, 2, 9])

indices = np.where(arr > 5)

print(indices)

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.vstack((a, b))

print(stacked)

