# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7bgZSFo6j1vsgnQKwAHgg6MYENfKf6T
"""

import pandas as pd

df = pd.read_csv('test.csv')

df.head()

df.tail()

df.count()

df.isnull()

df.loc[1,'Variable_code']

df.iloc[1,5]

df.describe(include='all')

df = pd.read_csv('test.csv')
df[df['Year'] > 2014]

df.rename(columns={'Units':'UNIT'})

df.set_index('Value', inplace=True)

df.head()

df.reset_index(inplace=True)

df.isnull()

pd.crosstab(df['Year'], df['Units'])

import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3]}, index=['a', 'b', 'c'])
df2 = pd.DataFrame({'B': [4, 5, 6]}, index=['a', 'b', 'd'])

print(df1, "\n")
print(df2, "\n")

# joins on index
res = df1.join(df2, how='inner')
print(res)

df_cleaned = df.drop_duplicates()

print(df_cleaned)

"""Practices"""

import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

print(df)

import pandas as pd

df = pd.read_csv("test.csv")

print(df.head())

import pandas as pd

df = pd.read_csv("test.csv")

print(df.info())

import pandas as pd

data = {
    'Name': ['John', 'Anna'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

print(df['Name'])

import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

filtered = df[df['Age'] > 25]

print(filtered)

import pandas as pd

data = {
    'A': [1, 2, 3]
}

df = pd.DataFrame(data)

df['B'] = [4, 5, 6]

print(df)

import pandas as pd
import numpy as np

data = {
    'A': [1, np.nan, 3]
}

df = pd.DataFrame(data)

df_filled = df.fillna(0)

print(df_filled)

import pandas as pd

data = {
    'Department': ['HR', 'IT', 'HR', 'IT'],
    'Salary': [3000, 4000, 3500, 4500]
}

df = pd.DataFrame(data)

grouped = df.groupby('Department')['Salary'].mean()

print(grouped)

import pandas as pd

df = pd.read_csv("input.csv")

df.to_csv("output.csv", index=False)

print("CSV file written successfully")

import pandas as pd

data = {
    'Name': ['John', 'Anna', 'John', 'Mike'],
    'Age': [25, 30, 25, 35]
}

df = pd.DataFrame(data)

duplicates = df[df.duplicated()]

print(duplicates)

import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Anna', 'Mike']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Salary': [5000, 6000, 7000]
})

merged = pd.merge(df1, df2, on='ID')

print(merged)

import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike'],
    'Age': [25, 30, 22]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')

print(sorted_df)

import pandas as pd
import numpy as np

data = {
    'A': [1, np.nan, 3],
    'B': [4, 5, np.nan]
}

df = pd.DataFrame(data)

cleaned_df = df.fillna(df.mean())

print(cleaned_df)

import pandas as pd

data = {
    'Department': ['HR', 'IT', 'HR', 'IT'],
    'Employee': ['A', 'B', 'C', 'D'],
    'Salary': [3000, 4000, 3500, 4500]
}

df = pd.DataFrame(data)

pivot = df.pivot_table(
    values='Salary',
    index='Department',
    aggfunc='mean'
)

print(pivot)

import pandas as pd

data = {
    'Marks': [40, 50, 60]
}

df = pd.DataFrame(data)

df['Bonus'] = df['Marks'].apply(lambda x: x + 5)

print(df)

import pandas as pd

data = {
    'A': [1, 2],
    'B': [3, 4]
}

df = pd.DataFrame(data)

df.columns = ['Number1', 'Number2']

print(df)

import pandas as pd

data = {
    'Name': ['John', 'Anna'],
    'Age': [25, 30]
}

df = pd.DataFrame(data)

df.to_excel('output.xlsx', index=False)

print("Excel file exported successfully")

import pandas as pd

df = pd.DataFrame({
    'old_name': [1, 2, 3]
})

df.rename(columns={'old_name': 'new_name'}, inplace=True)

print(df)

import pandas as pd

df = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune']
})

print(df['City'].nunique())

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': [4, 5, np.nan]
})

null_rows = df[df.isnull().any(axis=1)]

print(null_rows)

import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 28],
    'Salary': [50000, 60000, 80000, 90000, 55000],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR'],
    'City': ['New York', 'Chicago', 'New York', 'Boston', 'Chicago']
})

print(df)

ages = df[df['Age'] > 30]
print(ages)

"""# AND Condition (&)"""

dept_wise = df[(df['Age'] > 30) & (df['Department']== 'IT')]
print(dept_wise)

"""# 3. OR Condition (|)"""

or_condition = df[(df['Age'] > 30) | (df['Department'] == 'IT')]
print(or_condition)

"""# NOT CONDITION"""

not_condition = df[~(df['Department']=='HR')]
print(not_condition)

nots_condition = df[df['Department']!='HR']
print(nots_condition)

# C. Filtering with Comparison Operators
# Operator	Meaning
# >	greater than
# <	less than
# >=	greater than equal
# <=	less than equal
# ==	equal
# !=	not equal

"""# D. Filtering Using .loc"""

using_loc = df.loc[df['Age'] > 30, ['Name', 'Salary']]
print(using_loc)